// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>

#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>



namespace example::analytics_service::app {

class ServiceGenerated;




  using WriteCycleAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsResultSink, std::exception_ptr>;
  using WriteJoinedAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::JoinedAnalyticsSink, std::exception_ptr>;
  using WriteHighValueAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::HighValueAnalyticsSink, std::exception_ptr>;
  using WriteStandardAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::StandardAnalyticsSink, std::exception_ptr>;
  using WriteSubstreamAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::SubstreamAnalyticsResultSink, std::exception_ptr>;



  struct WriteCycleAnalyticsSinkBinding final {
    using Endpoint = WriteCycleAnalyticsCustomSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      WriteCycleAnalyticsSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsEvent& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::analytics_service::types::AnalyticsEvent>::make(value));
      }
    };
  };
  struct WriteJoinedAnalyticsSinkBinding final {
    using Endpoint = WriteJoinedAnalyticsCustomSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      WriteJoinedAnalyticsSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      }
    };
  };
  struct WriteHighValueAnalyticsSinkBinding final {
    using Endpoint = WriteHighValueAnalyticsCustomSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      WriteHighValueAnalyticsSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      }
    };
  };
  struct WriteStandardAnalyticsSinkBinding final {
    using Endpoint = WriteStandardAnalyticsCustomSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      WriteStandardAnalyticsSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      }
    };
  };
  struct WriteSubstreamAnalyticsSinkBinding final {
    using Endpoint = WriteSubstreamAnalyticsCustomSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      WriteSubstreamAnalyticsSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      }
    };
  };

  struct ServiceBindings final {
    WriteCycleAnalyticsSinkBinding write_cycle_analytics;
    WriteJoinedAnalyticsSinkBinding write_joined_analytics;
    WriteHighValueAnalyticsSinkBinding write_high_value_analytics;
    WriteStandardAnalyticsSinkBinding write_standard_analytics;
    WriteSubstreamAnalyticsSinkBinding write_substream_analytics;
  };



}  // namespace example::analytics_service::app