// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::analytics_service::app {

void ServiceEndpoints::initDataSinks(ServiceGenerated& service, const config::Config& cfg) {
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& endpoints_ = *this;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  auto& bindings_ = service.bindings_;
  (void)streams_; (void)functions_; (void)endpoints_; (void)connectors_;
  (void)clients_; (void)servers_; (void)bindings_;

  (void)cfg;



  endpoints_.write_cycle_analytics =
      std::make_shared<WriteCycleAnalyticsCustomSinkEndpoint>(
          streams_.write_cycle_analytics.get(),
          *functions_.cycle_analytics_result_sink);
  bindings_.write_cycle_analytics.consume =
      [endpoint = endpoints_.write_cycle_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsEvent& value) {
        return endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsEvent>::make(value));
      };
  service.registerDataSink(endpoints_.write_cycle_analytics);
  endpoints_.write_joined_analytics =
      std::make_shared<WriteJoinedAnalyticsCustomSinkEndpoint>(
          streams_.write_joined_analytics.get(),
          *functions_.joined_analytics_sink);
  bindings_.write_joined_analytics.consume =
      [endpoint = endpoints_.write_joined_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        return endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  service.registerDataSink(endpoints_.write_joined_analytics);
  endpoints_.write_high_value_analytics =
      std::make_shared<WriteHighValueAnalyticsCustomSinkEndpoint>(
          streams_.write_high_value_analytics.get(),
          *functions_.high_value_analytics_sink);
  bindings_.write_high_value_analytics.consume =
      [endpoint = endpoints_.write_high_value_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        return endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  service.registerDataSink(endpoints_.write_high_value_analytics);
  endpoints_.write_standard_analytics =
      std::make_shared<WriteStandardAnalyticsCustomSinkEndpoint>(
          streams_.write_standard_analytics.get(),
          *functions_.standard_analytics_sink);
  bindings_.write_standard_analytics.consume =
      [endpoint = endpoints_.write_standard_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        return endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  service.registerDataSink(endpoints_.write_standard_analytics);
  endpoints_.write_substream_analytics =
      std::make_shared<WriteSubstreamAnalyticsCustomSinkEndpoint>(
          streams_.write_substream_analytics.get(),
          *functions_.substream_analytics_result_sink);
  bindings_.write_substream_analytics.consume =
      [endpoint = endpoints_.write_substream_analytics.get()](
          servicelib::MessageContext context, const example::analytics_service::types::AnalyticsResult& value) {
        return endpoint->consume(std::move(context),
                          servicelib::Payload<example::analytics_service::types::AnalyticsResult>::make(value));
      };
  service.registerDataSink(endpoints_.write_substream_analytics);
}

void ServiceEndpoints::initDataSources(ServiceGenerated& service, const config::Config& cfg) {
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& endpoints_ = *this;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  auto& bindings_ = service.bindings_;
  (void)streams_; (void)functions_; (void)endpoints_; (void)connectors_;
  (void)clients_; (void)servers_; (void)bindings_;

  (void)cfg;


  connectors_.consume_order_processed_consumer =
      std::make_unique<ConsumeOrderProcessedKafkaConsumerOwner>(
          service, cfg.endpoints.orderProcessed.id);
  endpoints_.consume_order_processed = ConsumeOrderProcessedKafkaSourceEndpoint::make(
      service, *streams_.consume_order_processed, connectors_.consume_order_processed_consumer->client,
      *functions_.order_processed_endpoint_source);
  service.registerDataSource(endpoints_.consume_order_processed);

  endpoints_.analytics_orders = AnalyticsOrdersCustomSourceEndpoint::make(
      service, *streams_.analytics_orders,
      *functions_.analytics_orders_source,
      *functions_.analytics_orders_source);
  service.registerDataSource(endpoints_.analytics_orders);
  endpoints_.analytics_payments = AnalyticsPaymentsCustomSourceEndpoint::make(
      service, *streams_.analytics_payments,
      *functions_.analytics_payments_source,
      *functions_.analytics_payments_source);
  service.registerDataSource(endpoints_.analytics_payments);
  endpoints_.analytics_shipments = AnalyticsShipmentsCustomSourceEndpoint::make(
      service, *streams_.analytics_shipments,
      *functions_.analytics_shipments_source,
      *functions_.analytics_shipments_source);
  service.registerDataSource(endpoints_.analytics_shipments);
  endpoints_.cycle_analytics_input = CycleAnalyticsInputCustomSourceEndpoint::make(
      service, *streams_.cycle_analytics_input,
      *functions_.cycle_analytics_input_source,
      *functions_.cycle_analytics_input_source);
  service.registerDataSource(endpoints_.cycle_analytics_input);
  endpoints_.substream_analytics_input = SubstreamAnalyticsInputCustomSourceEndpoint::make(
      service, *streams_.substream_analytics_input,
      *functions_.substream_analytics_input_source,
      *functions_.substream_analytics_input_source);
  service.registerDataSource(endpoints_.substream_analytics_input);
  connectors_.local_cron_cron_source =
      servicelib::datasource::cron::LibcronDataSource::make(
          service, cfg.dataConnectors.localCron.id);
  endpoints_.analytics_schedule =
      servicelib::datasource::cron::Endpoint::make(
          service, *streams_.analytics_schedule, *functions_.analytics_schedule_source);
  connectors_.local_cron_cron_source->addEndpoint(endpoints_.analytics_schedule);
  service.registerDataSource(connectors_.local_cron_cron_source);

}



}  // namespace example::analytics_service::app