// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>


#include "analyticsservice/internal/app/streams.generated.hpp"

namespace example::analytics_service::app {

class ServiceGenerated;





  using ConsumeOrderProcessedKafkaSourceEndpoint =
      servicelib::datasource::kafka::Endpoint<
          example::model::types::OrderProcessed, example::model::types::OrderProcessed, functions::OrderProcessedEndpointSource, std::exception_ptr>;
  struct ConsumeOrderProcessedKafkaConsumerOwner final {
    ConsumeOrderProcessedKafkaConsumerOwner(
        servicelib::IServiceEnvironment& environment, int endpoint_id)
        : client(environment, endpoint_id) {}

    servicelib::datasource::kafka::LibrdkafkaConsumerClient client;
  };


  using AnalyticsOrdersCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsOrdersSource, std::exception_ptr>;
  using AnalyticsPaymentsCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsPaymentsSource, std::exception_ptr>;
  using AnalyticsShipmentsCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsShipmentsSource, std::exception_ptr>;
  using CycleAnalyticsInputCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsInputSource, std::exception_ptr>;
  using SubstreamAnalyticsInputCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::SubstreamAnalyticsInputSource, std::exception_ptr>;

  using WriteCycleAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsResultSink, std::exception_ptr>;
  using WriteJoinedAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::JoinedAnalyticsSink, std::exception_ptr>;
  using WriteHighValueAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::HighValueAnalyticsSink, std::exception_ptr>;
  using WriteStandardAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::StandardAnalyticsSink, std::exception_ptr>;
  using WriteSubstreamAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::SubstreamAnalyticsResultSink, std::exception_ptr>;


  struct ServiceEndpoints final {
    std::shared_ptr<ConsumeOrderProcessedKafkaSourceEndpoint> consume_order_processed;
    std::shared_ptr<AnalyticsOrdersCustomSourceEndpoint> analytics_orders;
    std::shared_ptr<AnalyticsPaymentsCustomSourceEndpoint> analytics_payments;
    std::shared_ptr<AnalyticsShipmentsCustomSourceEndpoint> analytics_shipments;
    std::shared_ptr<CycleAnalyticsInputCustomSourceEndpoint> cycle_analytics_input;
    std::shared_ptr<SubstreamAnalyticsInputCustomSourceEndpoint> substream_analytics_input;
    std::shared_ptr<servicelib::datasource::cron::Endpoint> analytics_schedule;
    std::shared_ptr<WriteCycleAnalyticsCustomSinkEndpoint> write_cycle_analytics;
    std::shared_ptr<WriteJoinedAnalyticsCustomSinkEndpoint> write_joined_analytics;
    std::shared_ptr<WriteHighValueAnalyticsCustomSinkEndpoint> write_high_value_analytics;
    std::shared_ptr<WriteStandardAnalyticsCustomSinkEndpoint> write_standard_analytics;
    std::shared_ptr<WriteSubstreamAnalyticsCustomSinkEndpoint> write_substream_analytics;

  void initDataSinks(ServiceGenerated& service, const config::Config& cfg);
  void initDataSources(ServiceGenerated& service, const config::Config& cfg);
};

}  // namespace example::analytics_service::app