// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>


#include "analyticsservice/internal/app/makers.generated.hpp"

namespace example::analytics_service::app {

class ServiceGenerated;

struct ServiceFunctions final {
  std::unique_ptr<functions::AdvanceCycleAnalytics> advance_cycle_analytics;
  std::unique_ptr<functions::AnalyticsOrdersSource> analytics_orders_source;
  std::unique_ptr<functions::AnalyticsPaymentsSource> analytics_payments_source;
  std::unique_ptr<functions::AnalyticsScheduleSource> analytics_schedule_source;
  std::unique_ptr<functions::AnalyticsShipmentsSource> analytics_shipments_source;
  std::unique_ptr<functions::BuildSubstreamAnalyticsResult> build_substream_analytics_result;
  std::unique_ptr<functions::CompleteCycleAnalytics> complete_cycle_analytics;
  std::unique_ptr<functions::ContinueCycleAnalytics> continue_cycle_analytics;
  std::unique_ptr<functions::CountOrderProcessed> count_order_processed;
  std::unique_ptr<functions::CycleAnalyticsInputSource> cycle_analytics_input_source;
  std::unique_ptr<functions::CycleAnalyticsResultSink> cycle_analytics_result_sink;
  std::unique_ptr<functions::HighValueAnalyticsSink> high_value_analytics_sink;
  std::unique_ptr<functions::InvokeAnalyticsSubstream> invoke_analytics_substream;
  std::unique_ptr<functions::JoinOrderPaymentAnalytics> join_order_payment_analytics;
  std::unique_ptr<functions::JoinedAnalyticsSink> joined_analytics_sink;
  std::unique_ptr<functions::KeyOrdersForJoin> key_orders_for_join;
  std::unique_ptr<functions::KeyOrdersForMultiJoin> key_orders_for_multi_join;
  std::unique_ptr<functions::KeyPaymentsForJoin> key_payments_for_join;
  std::unique_ptr<functions::KeyPaymentsForMultiJoin> key_payments_for_multi_join;
  std::unique_ptr<functions::KeyShipmentsForMultiJoin> key_shipments_for_multi_join;
  std::unique_ptr<functions::MultiJoinAnalyticsEvents> multi_join_analytics_events;
  std::unique_ptr<functions::OrderProcessedEndpointSource> order_processed_endpoint_source;
  std::unique_ptr<functions::RouteAnalyticsResult> route_analytics_result;
  std::unique_ptr<functions::StandardAnalyticsSink> standard_analytics_sink;
  std::unique_ptr<functions::SubstreamAnalyticsInputSource> substream_analytics_input_source;
  std::unique_ptr<functions::SubstreamAnalyticsResultSink> substream_analytics_result_sink;
  boost::asio::awaitable<void> initFunctions(servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment,
                     ServiceMakers& makers_, boost::asio::any_io_executor executor);
};

}  // namespace example::analytics_service::app