// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/functions.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <servicelib/runtime/detail/initialization.hpp>

namespace example::analytics_service::app {

boost::asio::awaitable<void> ServiceFunctions::initFunctions(
    servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment,
    ServiceMakers& makers_, boost::asio::any_io_executor executor) {
  (void)context;
  (void)cfg;
  (void)environment;
  (void)makers_;
  (void)executor;
  {
    if (!makers_.advance_cycle_analytics) {
      throw std::logic_error("function maker AdvanceCycleAnalytics is not configured");
    }
    if (!makers_.analytics_orders_source) {
      throw std::logic_error("function maker AnalyticsOrdersSource is not configured");
    }
    if (!makers_.analytics_payments_source) {
      throw std::logic_error("function maker AnalyticsPaymentsSource is not configured");
    }
    if (!makers_.analytics_schedule_source) {
      throw std::logic_error("function maker AnalyticsScheduleSource is not configured");
    }
    if (!makers_.analytics_shipments_source) {
      throw std::logic_error("function maker AnalyticsShipmentsSource is not configured");
    }
    if (!makers_.build_substream_analytics_result) {
      throw std::logic_error("function maker BuildSubstreamAnalyticsResult is not configured");
    }
    if (!makers_.complete_cycle_analytics) {
      throw std::logic_error("function maker CompleteCycleAnalytics is not configured");
    }
    if (!makers_.continue_cycle_analytics) {
      throw std::logic_error("function maker ContinueCycleAnalytics is not configured");
    }
    if (!makers_.count_order_processed) {
      throw std::logic_error("function maker CountOrderProcessed is not configured");
    }
    if (!makers_.cycle_analytics_input_source) {
      throw std::logic_error("function maker CycleAnalyticsInputSource is not configured");
    }
    if (!makers_.cycle_analytics_result_sink) {
      throw std::logic_error("function maker CycleAnalyticsResultSink is not configured");
    }
    if (!makers_.high_value_analytics_sink) {
      throw std::logic_error("function maker HighValueAnalyticsSink is not configured");
    }
    if (!makers_.invoke_analytics_substream) {
      throw std::logic_error("function maker InvokeAnalyticsSubstream is not configured");
    }
    if (!makers_.join_order_payment_analytics) {
      throw std::logic_error("function maker JoinOrderPaymentAnalytics is not configured");
    }
    if (!makers_.joined_analytics_sink) {
      throw std::logic_error("function maker JoinedAnalyticsSink is not configured");
    }
    if (!makers_.key_orders_for_join) {
      throw std::logic_error("function maker KeyOrdersForJoin is not configured");
    }
    if (!makers_.key_orders_for_multi_join) {
      throw std::logic_error("function maker KeyOrdersForMultiJoin is not configured");
    }
    if (!makers_.key_payments_for_join) {
      throw std::logic_error("function maker KeyPaymentsForJoin is not configured");
    }
    if (!makers_.key_payments_for_multi_join) {
      throw std::logic_error("function maker KeyPaymentsForMultiJoin is not configured");
    }
    if (!makers_.key_shipments_for_multi_join) {
      throw std::logic_error("function maker KeyShipmentsForMultiJoin is not configured");
    }
    if (!makers_.multi_join_analytics_events) {
      throw std::logic_error("function maker MultiJoinAnalyticsEvents is not configured");
    }
    if (!makers_.order_processed_endpoint_source) {
      throw std::logic_error("function maker OrderProcessedEndpointSource is not configured");
    }
    if (!makers_.route_analytics_result) {
      throw std::logic_error("function maker RouteAnalyticsResult is not configured");
    }
    if (!makers_.standard_analytics_sink) {
      throw std::logic_error("function maker StandardAnalyticsSink is not configured");
    }
    if (!makers_.substream_analytics_input_source) {
      throw std::logic_error("function maker SubstreamAnalyticsInputSource is not configured");
    }
    if (!makers_.substream_analytics_result_sink) {
      throw std::logic_error("function maker SubstreamAnalyticsResultSink is not configured");
    }
    std::stop_source maker_cancellation;
    std::mutex maker_error_mutex;
    std::exception_ptr first_maker_error;
    const auto maker_context = context.withExternalCancellation(maker_cancellation.get_token());
    std::vector<boost::asio::awaitable<void>> maker_tasks;
    maker_tasks.reserve(26);
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->advance_cycle_analytics = co_await makers->advance_cycle_analytics(maker_context, *environment);
            if (!functions->advance_cycle_analytics) {
              throw std::logic_error("function maker AdvanceCycleAnalytics returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->analytics_orders_source = co_await makers->analytics_orders_source(maker_context, *environment, cfg->endpoints.analyticsOrders);
            if (!functions->analytics_orders_source) {
              throw std::logic_error("function maker AnalyticsOrdersSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->analytics_payments_source = co_await makers->analytics_payments_source(maker_context, *environment, cfg->endpoints.analyticsPayments);
            if (!functions->analytics_payments_source) {
              throw std::logic_error("function maker AnalyticsPaymentsSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->analytics_schedule_source = co_await makers->analytics_schedule_source(maker_context, *environment, cfg->endpoints.analyticsSchedule);
            if (!functions->analytics_schedule_source) {
              throw std::logic_error("function maker AnalyticsScheduleSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->analytics_shipments_source = co_await makers->analytics_shipments_source(maker_context, *environment, cfg->endpoints.analyticsShipments);
            if (!functions->analytics_shipments_source) {
              throw std::logic_error("function maker AnalyticsShipmentsSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->build_substream_analytics_result = co_await makers->build_substream_analytics_result(maker_context, *environment);
            if (!functions->build_substream_analytics_result) {
              throw std::logic_error("function maker BuildSubstreamAnalyticsResult returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->complete_cycle_analytics = co_await makers->complete_cycle_analytics(maker_context, *environment);
            if (!functions->complete_cycle_analytics) {
              throw std::logic_error("function maker CompleteCycleAnalytics returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->continue_cycle_analytics = co_await makers->continue_cycle_analytics(maker_context, *environment);
            if (!functions->continue_cycle_analytics) {
              throw std::logic_error("function maker ContinueCycleAnalytics returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->count_order_processed = co_await makers->count_order_processed(maker_context, *environment);
            if (!functions->count_order_processed) {
              throw std::logic_error("function maker CountOrderProcessed returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->cycle_analytics_input_source = co_await makers->cycle_analytics_input_source(maker_context, *environment, cfg->endpoints.cycleAnalyticsInput);
            if (!functions->cycle_analytics_input_source) {
              throw std::logic_error("function maker CycleAnalyticsInputSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->cycle_analytics_result_sink = co_await makers->cycle_analytics_result_sink(maker_context, *environment, cfg->endpoints.cycleAnalyticsResult);
            if (!functions->cycle_analytics_result_sink) {
              throw std::logic_error("function maker CycleAnalyticsResultSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->high_value_analytics_sink = co_await makers->high_value_analytics_sink(maker_context, *environment, cfg->endpoints.highValueAnalytics);
            if (!functions->high_value_analytics_sink) {
              throw std::logic_error("function maker HighValueAnalyticsSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->invoke_analytics_substream = co_await makers->invoke_analytics_substream(maker_context, *environment);
            if (!functions->invoke_analytics_substream) {
              throw std::logic_error("function maker InvokeAnalyticsSubstream returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->join_order_payment_analytics = co_await makers->join_order_payment_analytics(maker_context, *environment);
            if (!functions->join_order_payment_analytics) {
              throw std::logic_error("function maker JoinOrderPaymentAnalytics returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->joined_analytics_sink = co_await makers->joined_analytics_sink(maker_context, *environment, cfg->endpoints.joinedAnalytics);
            if (!functions->joined_analytics_sink) {
              throw std::logic_error("function maker JoinedAnalyticsSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->key_orders_for_join = co_await makers->key_orders_for_join(maker_context, *environment);
            if (!functions->key_orders_for_join) {
              throw std::logic_error("function maker KeyOrdersForJoin returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->key_orders_for_multi_join = co_await makers->key_orders_for_multi_join(maker_context, *environment);
            if (!functions->key_orders_for_multi_join) {
              throw std::logic_error("function maker KeyOrdersForMultiJoin returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->key_payments_for_join = co_await makers->key_payments_for_join(maker_context, *environment);
            if (!functions->key_payments_for_join) {
              throw std::logic_error("function maker KeyPaymentsForJoin returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->key_payments_for_multi_join = co_await makers->key_payments_for_multi_join(maker_context, *environment);
            if (!functions->key_payments_for_multi_join) {
              throw std::logic_error("function maker KeyPaymentsForMultiJoin returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->key_shipments_for_multi_join = co_await makers->key_shipments_for_multi_join(maker_context, *environment);
            if (!functions->key_shipments_for_multi_join) {
              throw std::logic_error("function maker KeyShipmentsForMultiJoin returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->multi_join_analytics_events = co_await makers->multi_join_analytics_events(maker_context, *environment);
            if (!functions->multi_join_analytics_events) {
              throw std::logic_error("function maker MultiJoinAnalyticsEvents returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->order_processed_endpoint_source = co_await makers->order_processed_endpoint_source(maker_context, *environment, cfg->endpoints.orderProcessed);
            if (!functions->order_processed_endpoint_source) {
              throw std::logic_error("function maker OrderProcessedEndpointSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->route_analytics_result = co_await makers->route_analytics_result(maker_context, *environment);
            if (!functions->route_analytics_result) {
              throw std::logic_error("function maker RouteAnalyticsResult returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->standard_analytics_sink = co_await makers->standard_analytics_sink(maker_context, *environment, cfg->endpoints.standardAnalytics);
            if (!functions->standard_analytics_sink) {
              throw std::logic_error("function maker StandardAnalyticsSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->substream_analytics_input_source = co_await makers->substream_analytics_input_source(maker_context, *environment, cfg->endpoints.substreamAnalyticsInput);
            if (!functions->substream_analytics_input_source) {
              throw std::logic_error("function maker SubstreamAnalyticsInputSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->substream_analytics_result_sink = co_await makers->substream_analytics_result_sink(maker_context, *environment, cfg->endpoints.substreamAnalyticsResult);
            if (!functions->substream_analytics_result_sink) {
              throw std::logic_error("function maker SubstreamAnalyticsResultSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    try {
      co_await servicelib::detail::AwaitInitializationGroup(executor, std::move(maker_tasks), maker_cancellation);
    } catch (...) {
      if (!first_maker_error) first_maker_error = std::current_exception();
    }
    maker_cancellation.request_stop();
    if (first_maker_error) std::rethrow_exception(first_maker_error);
  }
}

}  // namespace example::analytics_service::app