// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>



namespace example::analytics_service::app {

class ServiceGenerated;

struct ServiceMakers final {
  std::function<boost::asio::awaitable<std::unique_ptr<functions::AdvanceCycleAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> advance_cycle_analytics;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::AnalyticsOrdersSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> analytics_orders_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::AnalyticsPaymentsSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> analytics_payments_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::AnalyticsScheduleSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CronEndpointConfig&)> analytics_schedule_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::AnalyticsShipmentsSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> analytics_shipments_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::BuildSubstreamAnalyticsResult>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> build_substream_analytics_result;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::CompleteCycleAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> complete_cycle_analytics;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::ContinueCycleAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> continue_cycle_analytics;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::CountOrderProcessed>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> count_order_processed;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::CycleAnalyticsInputSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> cycle_analytics_input_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::CycleAnalyticsResultSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> cycle_analytics_result_sink;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::HighValueAnalyticsSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> high_value_analytics_sink;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::InvokeAnalyticsSubstream>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> invoke_analytics_substream;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::JoinOrderPaymentAnalytics>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> join_order_payment_analytics;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::JoinedAnalyticsSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> joined_analytics_sink;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::KeyOrdersForJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> key_orders_for_join;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::KeyOrdersForMultiJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> key_orders_for_multi_join;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::KeyPaymentsForJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> key_payments_for_join;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::KeyPaymentsForMultiJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> key_payments_for_multi_join;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::KeyShipmentsForMultiJoin>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> key_shipments_for_multi_join;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::MultiJoinAnalyticsEvents>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> multi_join_analytics_events;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::OrderProcessedEndpointSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::RouteAnalyticsResult>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> route_analytics_result;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::StandardAnalyticsSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> standard_analytics_sink;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::SubstreamAnalyticsInputSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> substream_analytics_input_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::SubstreamAnalyticsResultSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::CustomEndpointConfig&)> substream_analytics_result_sink;
    std::function<boost::asio::awaitable<
        std::shared_ptr<servicelib::http::Router>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&)> http_router;
    std::function<boost::asio::awaitable<
        std::unique_ptr<servicelib::http::Server>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&,
        std::shared_ptr<servicelib::http::Router>)> http_server;


  void initMakers(boost::asio::any_io_executor executor);
};

}  // namespace example::analytics_service::app