// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/makers.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::analytics_service::app {

void ServiceMakers::initMakers(boost::asio::any_io_executor executor) {
  auto& makers_ = *this;
  makers_.advance_cycle_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeAdvanceCycleAnalytics(std::move(context), environment);
  };
  makers_.analytics_orders_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeAnalyticsOrdersSource(std::move(context), environment, config);
  };
  makers_.analytics_payments_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeAnalyticsPaymentsSource(std::move(context), environment, config);
  };
  makers_.analytics_schedule_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CronEndpointConfig& config) {
    return functions::MakeAnalyticsScheduleSource(std::move(context), environment, config);
  };
  makers_.analytics_shipments_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeAnalyticsShipmentsSource(std::move(context), environment, config);
  };
  makers_.build_substream_analytics_result = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeBuildSubstreamAnalyticsResult(std::move(context), environment);
  };
  makers_.complete_cycle_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeCompleteCycleAnalytics(std::move(context), environment);
  };
  makers_.continue_cycle_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeContinueCycleAnalytics(std::move(context), environment);
  };
  makers_.count_order_processed = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeCountOrderProcessed(std::move(context), environment);
  };
  makers_.cycle_analytics_input_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeCycleAnalyticsInputSource(std::move(context), environment, config);
  };
  makers_.cycle_analytics_result_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeCycleAnalyticsResultSink(std::move(context), environment, config);
  };
  makers_.high_value_analytics_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeHighValueAnalyticsSink(std::move(context), environment, config);
  };
  makers_.invoke_analytics_substream = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeInvokeAnalyticsSubstream(std::move(context), environment);
  };
  makers_.join_order_payment_analytics = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeJoinOrderPaymentAnalytics(std::move(context), environment);
  };
  makers_.joined_analytics_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeJoinedAnalyticsSink(std::move(context), environment, config);
  };
  makers_.key_orders_for_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyOrdersForJoin(std::move(context), environment);
  };
  makers_.key_orders_for_multi_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyOrdersForMultiJoin(std::move(context), environment);
  };
  makers_.key_payments_for_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyPaymentsForJoin(std::move(context), environment);
  };
  makers_.key_payments_for_multi_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyPaymentsForMultiJoin(std::move(context), environment);
  };
  makers_.key_shipments_for_multi_join = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeKeyShipmentsForMultiJoin(std::move(context), environment);
  };
  makers_.multi_join_analytics_events = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMultiJoinAnalyticsEvents(std::move(context), environment);
  };
  makers_.order_processed_endpoint_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::KafkaEndpointConfig& config) {
    return functions::MakeOrderProcessedEndpointSource(std::move(context), environment, config);
  };
  makers_.route_analytics_result = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeRouteAnalyticsResult(std::move(context), environment);
  };
  makers_.standard_analytics_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeStandardAnalyticsSink(std::move(context), environment, config);
  };
  makers_.substream_analytics_input_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeSubstreamAnalyticsInputSource(std::move(context), environment, config);
  };
  makers_.substream_analytics_result_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::CustomEndpointConfig& config) {
    return functions::MakeSubstreamAnalyticsResultSink(std::move(context), environment, config);
  };
  makers_.http_router = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config)
      -> boost::asio::awaitable<std::shared_ptr<servicelib::http::Router>> {
    (void)context;
    (void)environment;
    (void)config;
    co_return std::make_shared<servicelib::http::Router>();
  };
  makers_.http_server = [executor](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config,
      std::shared_ptr<servicelib::http::Router> router)
      -> boost::asio::awaitable<std::unique_ptr<servicelib::http::Server>> {
    (void)context;
    if (config.httpPort < 0 || config.httpPort > 65535) {
      throw std::invalid_argument("service HTTP port is out of range");
    }
    servicelib::http::Server::Options options;
    options.address = config.httpHost.empty() ? std::string{"0.0.0.0"}
                                               : config.httpHost;
    options.port = static_cast<std::uint16_t>(config.httpPort);
    options.tracingEnabled = environment.getTracing() != nullptr;
    options.shutdownTimeout =
        std::chrono::milliseconds{std::max(config.shutdownTimeout, 0)};
    co_return std::make_unique<servicelib::http::Server>(
        executor, std::move(router), std::move(options));
  };

}


}  // namespace example::analytics_service::app