// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>


#include "analyticsservice/internal/app/bindings.generated.hpp"

namespace example::analytics_service::app {

class ServiceGenerated;

  using AnalyticsScheduleInput =
      servicelib::InputStream<std::string, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using ConsumeOrderProcessedInput =
      servicelib::InputStream<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsOrdersInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsPaymentsInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsShipmentsInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using CycleAnalyticsInputInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using SubstreamAnalyticsInputInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;

  using CycleAnalyticsLinkCycle =
      servicelib::CycleLinkStream<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>;

struct ServiceFunctions;
struct ServiceStreams final {
  std::shared_ptr<servicelib::SubStream<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult, ServiceGenerated>> analyze_analytics_substream;
  servicelib::InputStream<std::string, std::monostate, std::exception_ptr, ServiceGenerated>* analytics_schedule{};
  servicelib::InputStream<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr, ServiceGenerated>* consume_order_processed{};
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* analytics_orders{};
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* analytics_payments{};
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* analytics_shipments{};
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* cycle_analytics_input{};
  servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr, ServiceGenerated>* substream_analytics_input{};
  servicelib::CycleLinkStream<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>* cycle_analytics_link{};
  servicelib::StreamBase* count_order_processed{nullptr};
  servicelib::StreamBase* split_analytics_orders{nullptr};
  servicelib::StreamBase* split_analytics_payments{nullptr};
  servicelib::StreamBase* merge_cycle_analytics{nullptr};
  servicelib::StreamBase* advance_cycle_analytics{nullptr};
  servicelib::StreamBase* split_cycle_analytics{nullptr};
  servicelib::StreamBase* complete_cycle_analytics{nullptr};
  servicelib::StreamBase* continue_cycle_analytics{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr> write_cycle_analytics;
  servicelib::StreamBase* key_orders_for_join{nullptr};
  servicelib::StreamBase* key_payments_for_join{nullptr};
  servicelib::StreamBase* join_order_payment_analytics{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_joined_analytics;
  servicelib::StreamBase* key_orders_for_multi_join{nullptr};
  servicelib::StreamBase* key_payments_for_multi_join{nullptr};
  servicelib::StreamBase* key_shipments_for_multi_join{nullptr};
  servicelib::StreamBase* multi_join_analytics_events{nullptr};
  servicelib::StreamBase* route_analytics_result{nullptr};
  servicelib::StreamBase* high_value_analytics{nullptr};
  servicelib::StreamBase* standard_analytics{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_high_value_analytics;
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_standard_analytics;
  servicelib::StreamBase* build_substream_analytics_result{nullptr};
  servicelib::StreamBase* invoke_analytics_substream{nullptr};
  servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_substream_analytics;

  void initStreams(const config::Config& cfg, ServiceGenerated& service);
  void build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions_, ServiceBindings& bindings_);
};

}  // namespace example::analytics_service::app