// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::analytics_service::app {

void ServiceSubStreams::bind(const ServiceStreams& streams) {
  (void)streams;
  analyze_analytics_substream_substream_->bind(streams.analyze_analytics_substream);
}

}  // namespace example::analytics_service::app