// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <atomic>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/substream_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/build_substream_analytics_result.hpp>
#include <analyticsservice/internal/functions/substreamanalytics/invoke_analytics_substream.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <example/model/types/automation_job.hpp>
#include <example/model/types/order_processed.hpp>



namespace example::analytics_service::app {

class ServiceGenerated;

// Business functions may retain handles without retaining the graph itself.
template <typename T, typename R>
class SubStreamHandle final : public servicelib::ISubStream<T, R> {
 public:
  void bind(const std::shared_ptr<servicelib::ISubStream<T, R>>& stream) {
    stream_.store(stream, std::memory_order_release);
  }

  boost::asio::awaitable<void> consume(servicelib::MessageContext context,
               servicelib::Payload<T> value,
               std::shared_ptr<servicelib::SubStreamCollector<R>> collector) override {
    auto stream = stream_.load(std::memory_order_acquire).lock();
    if (!stream) {
      throw std::logic_error("SubStream is not available: service is not running");
    }
    co_await stream->consume(std::move(context), std::move(value), std::move(collector));
  }

 private:
  std::atomic<std::weak_ptr<servicelib::ISubStream<T, R>>> stream_;
};


struct ServiceSubStreams final {
  std::shared_ptr<SubStreamHandle<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult>> analyze_analytics_substream_substream_ =
      std::make_shared<SubStreamHandle<example::analytics_service::types::AnalyticsEvent, example::analytics_service::types::AnalyticsResult>>();
  void bind(const struct ServiceStreams& streams);
};

}  // namespace example::analytics_service::app