// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <boost/json.hpp>

#include <stdexcept>
#include <string_view>

namespace handlers::order_service_api::processorder {

struct Request final {
  boost::json::object properties;
};

inline void tag_invoke(boost::json::value_from_tag,
                       boost::json::value& output,
                       const Request& request) {
  output = request.properties;
}

inline Request tag_invoke(boost::json::value_to_tag<Request>,
                          const boost::json::value& input) {
  if (!input.is_object()) {
    throw std::invalid_argument("OpenAPI request must be a JSON object");
  }
  return Request{input.as_object()};
}

inline void Validate(const Request&) {}

inline Request ParseRequest(std::string_view body) {
  auto request = boost::json::value_to<Request>(boost::json::parse(body));
  Validate(request);
  return request;
}

}  // namespace handlers::order_service_api::processorder