// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <boost/json.hpp>

#include <stdexcept>
#include <string>

namespace handlers::order_service_api::processorder {

struct Response final {
  boost::json::object properties;
};

inline void tag_invoke(boost::json::value_from_tag,
                       boost::json::value& output,
                       const Response& response) {
  output = response.properties;
}

inline Response tag_invoke(boost::json::value_to_tag<Response>,
                           const boost::json::value& input) {
  if (!input.is_object()) {
    throw std::invalid_argument("OpenAPI response must be a JSON object");
  }
  return Response{input.as_object()};
}

inline void Validate(const Response&) {}

inline std::string SerializeResponse(const Response& response) {
  Validate(response);
  return boost::json::serialize(boost::json::value_from(response));
}

}  // namespace handlers::order_service_api::processorder