// Code generated by servicegen. DO NOT EDIT.
#include <csignal>
#include <chrono>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>

#include <boost/asio/io_context.hpp>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>
#include <boost/asio/signal_set.hpp>

#include <servicelib/runtime/detail/coro_runtime.hpp>
#include <servicelib/runtime/config/command_line.hpp>
#include <servicelib/runtime/config/loader.hpp>
#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/environment_variable.hpp>
#include <servicelib/runtime/logging/logging.hpp>
#include <servicelib/runtime/telemetry/opentelemetry/opentelemetry.hpp>

#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/app/service.hpp"


namespace {

// Process policy, not runtime policy. Keep the watchdog alive through static
// destruction too: no cleanup stage may extend the one shutdown deadline.
void ArmShutdownDeadline(std::chrono::steady_clock::time_point deadline, int exit_code) noexcept {
  try {
    std::thread([deadline, exit_code] {
      std::this_thread::sleep_until(deadline);
      std::_Exit(exit_code);
    }).detach();
  } catch (...) {
    // Without a watchdog a blocked callback could prevent process termination.
    std::_Exit(exit_code);
  }
}

} // namespace

int main(int argc, char* argv[]) {
  try {

    const auto options = servicelib::config::CommandLine::Parse(argc, argv);
    using Config = example::analytics_service::config::Config;
    namespace otel = servicelib::telemetry::opentelemetry_adapter;
    using ServiceRuntime = servicelib::async::CoroRuntime;
    // A timed-out shutdown retains this complete host until admitted work
    // finishes. Destruction order keeps dependencies alive through the service.
    struct ServiceLifetime final {
      std::unique_ptr<servicelib::metrics::PrometheusMetrics> prometheus_metrics;
      std::unique_ptr<ServiceRuntime> runtime;
      std::unique_ptr<otel::OpenTelemetryLogger> otlp_logs;
      std::unique_ptr<otel::OpenTelemetryTracing> tracing;

      std::unique_ptr<example::analytics_service::app::Service> service;
    };
    auto lifetime = std::make_shared<ServiceLifetime>();
    const bool noop_logs =
        servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_LOGS");
    const bool noop_metrics =
        servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_METRICS");
    const bool noop_tracing =
        servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_TRACING");
    servicelib::log::Logger& bootstrap_logger =
        noop_logs
            ? servicelib::log::NoopLogger::instance()
            : servicelib::logging::createLogsEngine(
                  servicelib::logging::LogsEngineType::kBoost);
    auto& prometheus_metrics = lifetime->prometheus_metrics;
    servicelib::metrics::Metrics* metrics =
        &servicelib::metrics::NoopMetrics::instance();
    if (!noop_metrics) {
      prometheus_metrics =
          std::make_unique<servicelib::metrics::PrometheusMetrics>();
      metrics = prometheus_metrics.get();
    }
    servicelib::config::ConfigLoader<Config> loader(
        {.configPath = options.configPath,
         .overridePath = options.valuesPath},
        {}, bootstrap_logger, *metrics, "");
    const auto runtime_config = loader.Load();
    const auto config = loader.GetConfig();
    const auto& own_service_config =
        config->services.analyticsService;
    lifetime->runtime = std::make_unique<ServiceRuntime>(
        ServiceRuntime::Options{.workers = options.workers,
         .unhandledException = {}, .metrics = metrics,
         .blockingWorkers = options.workers});
    auto& runtime = *lifetime->runtime;
    runtime.start();
    auto& otlp_logs = lifetime->otlp_logs;
    auto& tracing = lifetime->tracing;
    servicelib::log::Logger* service_logger = &bootstrap_logger;
    switch (own_service_config.environment) {
      case servicelib::api::Environment::kStaging:
      case servicelib::api::Environment::kProduction:
        if (!noop_logs) {
          otlp_logs = otel::CreateOTLPLogsEngine(own_service_config.name);
          service_logger = otlp_logs.get();
        }
        if (!noop_tracing) {
          tracing =
              otel::CreateOTLPTracingEngine(own_service_config.name);
        }
        break;
      default:
        if (!noop_tracing) {
          tracing =
              otel::CreateStdoutTracingEngine(own_service_config.name);
        }
        break;
    }

    lifetime->service = std::make_unique<example::analytics_service::app::Service>(runtime.executor(),
                                    config, *service_logger,
                                    *metrics, tracing.get());
    auto& service = *lifetime->service;
    service.setShutdownLifetime(lifetime);
    auto shutdown_deadline = std::chrono::steady_clock::time_point::max();
    bool shutdown_deadline_started{};
    const auto begin_shutdown = [&](int exit_code) {
      if (shutdown_deadline_started) return;
      shutdown_deadline_started = true;
      const auto timeout = std::chrono::milliseconds(
          own_service_config.shutdownTimeout > 0
              ? own_service_config.shutdownTimeout
              : 0);
      shutdown_deadline = std::chrono::steady_clock::now() + timeout;
      ArmShutdownDeadline(shutdown_deadline, exit_code);
    };
    bool runtime_shutdown{};
    const auto shutdown_runtime = [&] {
      if (runtime_shutdown) return;
      begin_shutdown(EXIT_SUCCESS);
      loader.Stop();
      boost::asio::co_spawn(runtime.executor(),
          service.stop(servicelib::Context{}.withDeadline(shutdown_deadline)),
          boost::asio::use_future).get();
      boost::asio::co_spawn(runtime.executor(), service.waitStopped(),
          boost::asio::use_future).get();
      lifetime->service.reset();
      const bool tracing_flushed = !tracing || tracing->forceFlush();
      const bool tracing_stopped = !tracing || tracing->shutdown();
      const bool logs_flushed = !otlp_logs || otlp_logs->forceFlush();
      const bool logs_stopped = !otlp_logs || otlp_logs->shutdown();
      tracing.reset();
      otlp_logs.reset();
      runtime.stop();
      runtime.join();
      runtime_shutdown = true;
      if (!tracing_flushed || !tracing_stopped || !logs_flushed || !logs_stopped) {
        throw std::runtime_error("failed to flush OpenTelemetry providers");
      }
    };
    // The main thread waits for signals independently of business workers.
    // A blocked worker must not prevent the shutdown watchdog from starting.
    boost::asio::io_context shutdown_signals_context;
    boost::asio::signal_set shutdown_signals(shutdown_signals_context, SIGINT, SIGTERM);
    shutdown_signals.async_wait([&](const boost::system::error_code& error, int) {
      if (error) throw std::runtime_error("shutdown signal wait failed: " + error.message());
      begin_shutdown(EXIT_SUCCESS);
    });
    try {
      boost::asio::co_spawn(runtime.executor(), service.start(), boost::asio::use_future).get();
      loader.Start(std::chrono::seconds{5},
                   [](std::shared_ptr<const servicelib::config::RuntimeConfig>
                          next_config) {
                     servicelib::config::RuntimeConfigRegistry::Publish(
                         std::move(next_config));
                   });

      shutdown_signals_context.run();
      shutdown_runtime();
    } catch (...) {
      begin_shutdown(EXIT_FAILURE);
      try {
        shutdown_runtime();
      } catch (...) {
        // Preserve the original startup/runtime failure.
      }
      throw;
    }
    return 0;
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}