// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::inventory_service::app {

void ServiceEndpoints::initDataSources(ServiceGenerated& service, const config::Config& cfg) {
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& endpoints_ = *this;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  auto& bindings_ = service.bindings_;
  (void)streams_; (void)functions_; (void)endpoints_; (void)connectors_;
  (void)clients_; (void)servers_; (void)bindings_;

  (void)cfg;
  connectors_.inventory_service_api_source =
      servicelib::datasource::grpc::DataSource::make(
          service, *streams_.process_inventory_item);
  endpoints_.process_inventory_item = ProcessInventoryItemGrpcSourceConsumer::make(
      service, *streams_.process_inventory_item,
      *functions_.process_order_item_source);
  connectors_.inventory_service_api_source->addEndpoint(endpoints_.process_inventory_item->endpoint());
  service.registerDataSource(connectors_.inventory_service_api_source);




}



}  // namespace example::inventory_service::app