// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "inventoryservice/config/config.generated.hpp"
#include "inventoryservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/grpc/asio.hpp>
#include <servicelib/datasource/http/beast.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_error.hpp>
#include <inventoryservice/internal/types/inventory_failure.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


#include "inventoryservice/internal/app/streams.generated.hpp"

namespace example::inventory_service::app {

class ServiceGenerated;

  using ProcessInventoryItemGrpcSourceEndpoint =
      servicelib::datasource::grpc::NoStreamingEndpoint<
          ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSource, std::exception_ptr>;
  using ProcessInventoryItemGrpcSourceConsumer =
      servicelib::datasource::grpc::EndpointConsumer<
          ProcessInventoryItemInput, ProcessInventoryItemGrpcSourceEndpoint, functions::ProcessOrderItemSource>;









  struct ServiceEndpoints final {
    std::shared_ptr<ProcessInventoryItemGrpcSourceConsumer> process_inventory_item;

  void initDataSources(ServiceGenerated& service, const config::Config& cfg);
};

}  // namespace example::inventory_service::app