// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/functions.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <servicelib/runtime/detail/initialization.hpp>

namespace example::inventory_service::app {

boost::asio::awaitable<void> ServiceFunctions::initFunctions(
    servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment,
    ServiceMakers& makers_, boost::asio::any_io_executor executor) {
  (void)context;
  (void)cfg;
  (void)environment;
  (void)makers_;
  (void)executor;
  {
    if (!makers_.get_inventory_item_data) {
      throw std::logic_error("function maker GetInventoryItemData is not configured");
    }
    if (!makers_.get_inventory_item_error) {
      throw std::logic_error("function maker GetInventoryItemError is not configured");
    }
    if (!makers_.process_order_item_source) {
      throw std::logic_error("function maker ProcessOrderItemSource is not configured");
    }
    std::stop_source maker_cancellation;
    std::mutex maker_error_mutex;
    std::exception_ptr first_maker_error;
    const auto maker_context = context.withExternalCancellation(maker_cancellation.get_token());
    std::vector<boost::asio::awaitable<void>> maker_tasks;
    maker_tasks.reserve(3);
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->get_inventory_item_data = co_await makers->get_inventory_item_data(maker_context, *environment);
            if (!functions->get_inventory_item_data) {
              throw std::logic_error("function maker GetInventoryItemData returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->get_inventory_item_error = co_await makers->get_inventory_item_error(maker_context, *environment);
            if (!functions->get_inventory_item_error) {
              throw std::logic_error("function maker GetInventoryItemError returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->process_order_item_source = co_await makers->process_order_item_source(maker_context, *environment, cfg->endpoints.processOrderItem);
            if (!functions->process_order_item_source) {
              throw std::logic_error("function maker ProcessOrderItemSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    try {
      co_await servicelib::detail::AwaitInitializationGroup(executor, std::move(maker_tasks), maker_cancellation);
    } catch (...) {
      if (!first_maker_error) first_maker_error = std::current_exception();
    }
    maker_cancellation.request_stop();
    if (first_maker_error) std::rethrow_exception(first_maker_error);
  }
  co_return;
}

}  // namespace example::inventory_service::app