// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/grpc_service.generated.hpp"

#include <stdexcept>
#include <utility>

namespace example::inventory_service::app {

void GrpcServicesGenerated::registerServices(::grpc::ServerBuilder& builder) {
  builder.RegisterService(&inventory_service_api_service);
}

void GrpcServicesGenerated::registerHandlers(
    agrpc::GrpcContext& context, ServiceGenerated& service,
    boost::asio::any_io_executor executor) {
  servicelib::grpc_transport::RegisterUnarySource<
      &::inventoryserviceapi::InventoryServiceApi::AsyncService::RequestProcessOrderItem>(
      context, inventory_service_api_service,
      [&service](servicelib::MessageContext message,
                 const ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest& request)
          -> boost::asio::awaitable<::inventoryserviceapi::processorderitem::ProcessOrderItemResponse> {
        const auto endpoint = service.grpcSourceEndpointProcessInventoryItem();
        if (!endpoint) {
          throw std::runtime_error("gRPC datasource endpoint is not started");
        }
        co_return co_await endpoint->asyncHandle(std::move(message), request);
      }, executor);
}

}  // namespace example::inventory_service::app