// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <agrpc/grpc_context.hpp>
#include <boost/asio/any_io_executor.hpp>
#include <grpcpp/server_builder.h>

#include <servicelib/runtime/detail/grpc_streaming.hpp>

#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>

#include "inventoryservice/internal/app/service.hpp"

namespace example::inventory_service::app {

class GrpcServicesGenerated final {
 public:
  void registerServices(::grpc::ServerBuilder& builder);
  void registerHandlers(agrpc::GrpcContext& context,
                        ServiceGenerated& service,
                        boost::asio::any_io_executor executor);

 private:
  ::inventoryserviceapi::InventoryServiceApi::AsyncService inventory_service_api_service;
};

}  // namespace example::inventory_service::app