// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/grpc_service.generated.hpp"
#include <stdexcept>
#include <utility>
namespace example::inventory_service::app {
namespace {
template<class Reactor>
class UnavailableReactor final : public Reactor {
 public:
  UnavailableReactor() {
    this->Finish(::grpc::Status(::grpc::StatusCode::UNAVAILABLE, "service is not started"));
  }
  void OnDone() override { delete this; }
};
}
void GrpcServicesGenerated::registerServices(::grpc::ServerBuilder& builder) {
  builder.RegisterService(&inventory_service_api_service);
}
void GrpcServicesGenerated::registerHandlers(
    ServiceGenerated& service, boost::asio::any_io_executor executor) {
  inventory_service_api_service.binding.store(
      std::make_shared<const InventoryServiceApiGrpcService::Binding>(
          InventoryServiceApiGrpcService::Binding{&service, executor}));
}
::grpc::ServerUnaryReactor* GrpcServicesGenerated::InventoryServiceApiGrpcService::ProcessOrderItem(
    ::grpc::CallbackServerContext* context,
    const ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest* request,
        ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse* response) {
  auto current = binding.load();
  if (!current) {
    auto* reactor = context->DefaultReactor();
    reactor->Finish(::grpc::Status(::grpc::StatusCode::UNAVAILABLE, "service is not started"));
    return reactor;
  }
  return servicelib::grpc_transport::StartUnarySource(
      context, request, response, current->executor,
      [current](servicelib::MessageContext message,
                 const ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest& request)
          -> boost::asio::awaitable<::inventoryserviceapi::processorderitem::ProcessOrderItemResponse> {
        const auto endpoint = current->service->grpcSourceEndpointProcessInventoryItem();
        if (!endpoint) {
          throw std::runtime_error("gRPC datasource endpoint is not started");
        }
        co_return co_await endpoint->asyncHandle(std::move(message), request);
      });
}

}  // namespace example::inventory_service::app