// Code generated by servicegen. DO NOT EDIT.
#pragma once
#include <atomic>
#include <memory>

#include <boost/asio/any_io_executor.hpp>
#include <grpcpp/server_builder.h>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>

#include <servicelib/runtime/detail/grpc_callback_server.hpp>
#include <servicelib/runtime/detail/grpc_source_handlers.hpp>

#include "inventoryservice/internal/app/service.hpp"
namespace example::inventory_service::app {
class GrpcServicesGenerated final {
 public:
  void registerServices(::grpc::ServerBuilder& builder);
  void registerHandlers(ServiceGenerated& service, boost::asio::any_io_executor executor);
 private:
  class InventoryServiceApiGrpcService final : public ::inventoryserviceapi::InventoryServiceApi::CallbackService {
   public:
    struct Binding {
      ServiceGenerated* service;
      boost::asio::any_io_executor executor;
    };
    std::atomic<std::shared_ptr<const Binding>> binding;
    ::grpc::ServerUnaryReactor* ProcessOrderItem(
        ::grpc::CallbackServerContext* context,
        const ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest* request,
        ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse* response) override;
  } inventory_service_api_service;
};
}  // namespace example::inventory_service::app