// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/makers.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::inventory_service::app {

void ServiceMakers::initMakers(boost::asio::any_io_executor executor, agrpc::GrpcContext* grpc_context) {
  auto& makers_ = *this;
  makers_.get_inventory_item_data = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeGetInventoryItemData(std::move(context), environment);
  };
  makers_.get_inventory_item_error = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeGetInventoryItemError(std::move(context), environment);
  };
  makers_.process_order_item_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::GrpcEndpointConfig& config) {
    return functions::MakeProcessOrderItemSource(std::move(context), environment, config);
  };
  makers_.http_router = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config)
      -> boost::asio::awaitable<std::shared_ptr<servicelib::http::Router>> {
    (void)context;
    (void)environment;
    (void)config;
    co_return std::make_shared<servicelib::http::Router>();
  };
  makers_.http_server = [executor](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config,
      std::shared_ptr<servicelib::http::Router> router)
      -> boost::asio::awaitable<std::unique_ptr<servicelib::http::Server>> {
    (void)context;
    if (config.httpPort < 0 || config.httpPort > 65535) {
      throw std::invalid_argument("service HTTP port is out of range");
    }
    servicelib::http::Server::Options options;
    options.address = config.httpHost.empty() ? std::string{"0.0.0.0"}
                                               : config.httpHost;
    options.port = static_cast<std::uint16_t>(config.httpPort);
    options.tracingEnabled = environment.getTracing() != nullptr;
    options.shutdownTimeout =
        std::chrono::milliseconds{std::max(config.shutdownTimeout, 0)};
    co_return std::make_unique<servicelib::http::Server>(
        executor, std::move(router), std::move(options));
  };

}


}  // namespace example::inventory_service::app