// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "inventoryservice/config/config.generated.hpp"
#include "inventoryservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/grpc/asio.hpp>
#include <servicelib/datasource/http/beast.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_error.hpp>
#include <inventoryservice/internal/types/inventory_failure.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>



namespace example::inventory_service::app {

class ServiceGenerated;

struct ServiceMakers final {
  std::function<boost::asio::awaitable<std::unique_ptr<functions::GetInventoryItemData>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> get_inventory_item_data;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::GetInventoryItemError>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> get_inventory_item_error;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::ProcessOrderItemSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::GrpcEndpointConfig&)> process_order_item_source;
    std::function<boost::asio::awaitable<
        std::shared_ptr<servicelib::http::Router>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&)> http_router;
    std::function<boost::asio::awaitable<
        std::unique_ptr<servicelib::http::Server>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&,
        std::shared_ptr<servicelib::http::Router>)> http_server;


  void initMakers(boost::asio::any_io_executor executor, agrpc::GrpcContext* grpc_context);
};

}  // namespace example::inventory_service::app