// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/asio.hpp>
#include <servicelib/runtime/detail/grpc_client.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasink/kafka/librdkafka.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>



namespace example::order_service::app {

class ServiceGenerated;

  struct ProcessOrderItemSinkBinding final {
    std::function<boost::asio::awaitable<void>(servicelib::MessageContext, const example::model::types::OrderItem&)>
        consume;
    struct Function final {
      ProcessOrderItemSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::model::types::OrderItem& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->consume(std::move(context), value);
      }
    };
  };
  struct PublishOrderProcessedSinkBinding final {
    std::function<boost::asio::awaitable<void>(servicelib::MessageContext, const example::model::types::OrderProcessed&)>
        consume;
    struct Function final {
      PublishOrderProcessedSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::model::types::OrderProcessed& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->consume(std::move(context), value);
      }
    };
  };

  struct ServiceBindings final {
    ProcessOrderItemSinkBinding process_order_item;
    PublishOrderProcessedSinkBinding publish_order_processed;
  };



}  // namespace example::order_service::app