// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <boost/asio/io_context.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>

#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/asio.hpp>
#include <servicelib/runtime/detail/grpc_callback_client.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasink/kafka/librdkafka.hpp>

#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>



namespace example::order_service::app {

class ServiceGenerated;

  struct ProcessOrderItemGrpcClientFunction final {
    servicelib::grpc_transport::callback::ClientPool<::inventoryserviceapi::InventoryServiceApi::Stub>* client;
    boost::asio::awaitable<::inventoryserviceapi::processorderitem::ProcessOrderItemResponse> operator()(
        ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest request,
        servicelib::datasink::grpc::CallOptions options) const {
      return client->template unary<::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse>(
          std::move(request), std::move(options),
          [](auto& stub, auto* context, const auto* value, auto* response, auto done) {
            stub.async()->ProcessOrderItem(context, value, response, std::move(done));
          });
    }
  };
  using ProcessOrderItemGrpcSinkEndpoint =
      servicelib::datasink::grpc::NoStreamingEndpoint<
          ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSink, ProcessOrderItemGrpcClientFunction, example::order_service::types::OrderState>;


  using PublishOrderProcessedKafkaSinkEndpoint =
      servicelib::datasink::kafka::Endpoint<
          example::model::types::OrderProcessed, std::monostate, functions::OrderProcessedEndpointSink, std::exception_ptr>;




  struct ProcessOrderItemSinkBinding final {
    using Endpoint = ProcessOrderItemGrpcSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      ProcessOrderItemSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::model::types::OrderItem& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::model::types::OrderItem>::make(value));
      }
    };
  };
  struct PublishOrderProcessedSinkBinding final {
    using Endpoint = PublishOrderProcessedKafkaSinkEndpoint;
    Endpoint* endpoint{};
    struct Function final {
      PublishOrderProcessedSinkBinding* binding;
      boost::asio::awaitable<void> operator()(servicelib::MessageContext context,
                      const example::model::types::OrderProcessed& value) const {
        if (!binding->endpoint) {
          throw std::logic_error("sink endpoint is not bound");
        }
        return binding->endpoint->consume(
            std::move(context), servicelib::Payload<example::model::types::OrderProcessed>::make(value));
      }
    };
  };

  struct ServiceBindings final {
    ProcessOrderItemSinkBinding process_order_item;
    PublishOrderProcessedSinkBinding publish_order_processed;
  };



}  // namespace example::order_service::app