// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/asio.hpp>
#include <servicelib/runtime/detail/grpc_client.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasink/kafka/librdkafka.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


#include "orderservice/internal/app/streams.generated.hpp"

namespace example::order_service::app {

class ServiceGenerated;


  struct ProcessOrderItemGrpcClientFunction final {
    servicelib::grpc_transport::ClientPool<::inventoryserviceapi::InventoryServiceApi::Stub>* client;
    void async(
        ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest request,
        servicelib::datasink::grpc::CallOptions options,
        std::function<void(std::exception_ptr,
                           std::optional<::inventoryserviceapi::processorderitem::ProcessOrderItemResponse>)> completion) const {
      client->template asyncUnary<
          &::inventoryserviceapi::InventoryServiceApi::Stub::PrepareAsyncProcessOrderItem, ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest,
          ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse>(std::move(request), std::move(options),
                             std::move(completion));
    }
  };
  using ProcessOrderItemGrpcSinkEndpoint =
      servicelib::datasink::grpc::NoStreamingEndpoint<
          ::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, ::inventoryserviceapi::processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSink, ProcessOrderItemGrpcClientFunction, example::order_service::types::OrderState>;

  using ProcessOrderHTTPSourceConsumer =
      servicelib::datasource::http::BeastEndpointConsumer<
          example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
          ServiceGenerated, functions::ProcessOrderSource>;



  using PublishOrderProcessedKafkaSinkEndpoint =
      servicelib::datasink::kafka::Endpoint<
          example::model::types::OrderProcessed, std::monostate, functions::OrderProcessedEndpointSink, std::exception_ptr>;




  struct ServiceEndpoints final {
    std::shared_ptr<ProcessOrderItemGrpcSinkEndpoint> process_order_item;
    std::shared_ptr<ProcessOrderHTTPSourceConsumer> process_order;
    std::shared_ptr<PublishOrderProcessedKafkaSinkEndpoint> publish_order_processed;

  void initDataSinks(ServiceGenerated& service, const config::Config& cfg);
  void initDataSources(ServiceGenerated& service, const config::Config& cfg);
};

}  // namespace example::order_service::app