// Code generated by servicegen. DO NOT EDIT.
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>

#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

#include "orderservice/internal/app/service.generated.hpp"

namespace example::order_service::app {

void ServiceEndpoints::initDataSinks(ServiceGenerated& service, const config::Config& cfg) {
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& endpoints_ = *this;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  auto& bindings_ = service.bindings_;
  (void)streams_; (void)functions_; (void)endpoints_; (void)connectors_;
  (void)clients_; (void)servers_; (void)bindings_;

  (void)cfg;
  {
  }
  connectors_.inventory_service_api_sink =
      servicelib::datasink::grpc::DataSink::make(
          streams_.process_order_item.get());
  endpoints_.process_order_item = std::make_shared<ProcessOrderItemGrpcSinkEndpoint>(
      streams_.process_order_item.get(),
      *functions_.process_order_item_sink,
      ProcessOrderItemGrpcClientFunction{&*clients_.inventory_service_api_client});
  bindings_.process_order_item.endpoint = endpoints_.process_order_item.get();
  connectors_.inventory_service_api_sink->addEndpoint(endpoints_.process_order_item);
  service.registerDataSink(connectors_.inventory_service_api_sink);


  clients_.publish_order_processed_producer =
      std::make_unique<servicelib::datasink::kafka::LibrdkafkaProducerClient>(
          service.getMetrics());
  endpoints_.publish_order_processed = std::make_shared<PublishOrderProcessedKafkaSinkEndpoint>(
      streams_.publish_order_processed.get(), *clients_.publish_order_processed_producer,
      *functions_.order_processed_endpoint_sink);
  bindings_.publish_order_processed.endpoint = endpoints_.publish_order_processed.get();
  service.registerDataSink(endpoints_.publish_order_processed);

}

void ServiceEndpoints::initDataSources(ServiceGenerated& service, const config::Config& cfg) {
  auto& streams_ = service.streams_;
  auto& functions_ = service.functions_;
  auto& endpoints_ = *this;
  auto& connectors_ = service.connectors_;
  auto& clients_ = service.clients_;
  auto& servers_ = service.servers_;
  auto& bindings_ = service.bindings_;
  (void)streams_; (void)functions_; (void)endpoints_; (void)connectors_;
  (void)clients_; (void)servers_; (void)bindings_;

  (void)cfg;

  connectors_.order_service_api_source =
      servicelib::datasource::http::BeastDataSource::make(
          service, *streams_.process_order);
  endpoints_.process_order = ProcessOrderHTTPSourceConsumer::make(
      service, *streams_.process_order,
      *functions_.process_order_source);
  connectors_.order_service_api_source->addEndpoint(endpoints_.process_order->endpoint());
  connectors_.order_service_api_source->registerRoutes(*servers_.http_router_);
  service.registerDataSource(connectors_.order_service_api_source);



}



}  // namespace example::order_service::app