// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/functions.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <servicelib/runtime/detail/initialization.hpp>

namespace example::order_service::app {

boost::asio::awaitable<void> ServiceFunctions::initFunctions(
    servicelib::Context context, const config::Config& cfg, servicelib::IServiceEnvironment& environment,
    ServiceMakers& makers_, boost::asio::any_io_executor executor) {
  (void)context;
  (void)cfg;
  (void)environment;
  (void)makers_;
  (void)executor;
  {
    if (!makers_.map_order_item_result_to_order_state) {
      throw std::logic_error("function maker MapOrderItemResultToOrderState is not configured");
    }
    if (!makers_.map_to_order_processed) {
      throw std::logic_error("function maker MapToOrderProcessed is not configured");
    }
    if (!makers_.map_to_order_state) {
      throw std::logic_error("function maker MapToOrderState is not configured");
    }
    if (!makers_.order_processed_endpoint_sink) {
      throw std::logic_error("function maker OrderProcessedEndpointSink is not configured");
    }
    if (!makers_.process_order_item_sink) {
      throw std::logic_error("function maker ProcessOrderItemSink is not configured");
    }
    if (!makers_.process_order_items) {
      throw std::logic_error("function maker ProcessOrderItems is not configured");
    }
    if (!makers_.process_order_source) {
      throw std::logic_error("function maker ProcessOrderSource is not configured");
    }
    if (!makers_.soft_deadline) {
      throw std::logic_error("function maker SoftDeadline is not configured");
    }
    std::stop_source maker_cancellation;
    std::mutex maker_error_mutex;
    std::exception_ptr first_maker_error;
    const auto maker_context = context.withExternalCancellation(maker_cancellation.get_token());
    std::vector<boost::asio::awaitable<void>> maker_tasks;
    maker_tasks.reserve(8);
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->map_order_item_result_to_order_state = co_await makers->map_order_item_result_to_order_state(maker_context, *environment);
            if (!functions->map_order_item_result_to_order_state) {
              throw std::logic_error("function maker MapOrderItemResultToOrderState returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->map_to_order_processed = co_await makers->map_to_order_processed(maker_context, *environment);
            if (!functions->map_to_order_processed) {
              throw std::logic_error("function maker MapToOrderProcessed returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->map_to_order_state = co_await makers->map_to_order_state(maker_context, *environment);
            if (!functions->map_to_order_state) {
              throw std::logic_error("function maker MapToOrderState returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->order_processed_endpoint_sink = co_await makers->order_processed_endpoint_sink(maker_context, *environment, cfg->endpoints.orderProcessed);
            if (!functions->order_processed_endpoint_sink) {
              throw std::logic_error("function maker OrderProcessedEndpointSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->process_order_item_sink = co_await makers->process_order_item_sink(maker_context, *environment, cfg->endpoints.processOrderItem);
            if (!functions->process_order_item_sink) {
              throw std::logic_error("function maker ProcessOrderItemSink returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->process_order_items = co_await makers->process_order_items(maker_context, *environment);
            if (!functions->process_order_items) {
              throw std::logic_error("function maker ProcessOrderItems returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,
           const config::Config* cfg,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->process_order_source = co_await makers->process_order_source(maker_context, *environment, cfg->endpoints.processOrder);
            if (!functions->process_order_source) {
              throw std::logic_error("function maker ProcessOrderSource returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &cfg, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    maker_tasks.push_back(
        [](ServiceMakers* makers, ServiceFunctions* functions,
           servicelib::IServiceEnvironment* environment, servicelib::Context maker_context,

           std::stop_source* maker_cancellation, std::mutex* maker_error_mutex,
           std::exception_ptr* first_maker_error) -> boost::asio::awaitable<void> {
          try {
            functions->soft_deadline = co_await makers->soft_deadline(maker_context, *environment);
            if (!functions->soft_deadline) {
              throw std::logic_error("function maker SoftDeadline returned null");
            }
          } catch (...) {
            maker_cancellation->request_stop();
            const std::lock_guard lock(*maker_error_mutex);
            if (!*first_maker_error) *first_maker_error = std::current_exception();
            throw;
          }
          co_return;
        }(&makers_, this, &environment, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error));
    try {
      co_await servicelib::detail::AwaitInitializationGroup(executor, std::move(maker_tasks), maker_cancellation);
    } catch (...) {
      if (!first_maker_error) first_maker_error = std::current_exception();
    }
    maker_cancellation.request_stop();
    if (first_maker_error) std::rethrow_exception(first_maker_error);
  }
}

}  // namespace example::order_service::app