// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/makers.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::order_service::app {

void ServiceMakers::initMakers(boost::asio::any_io_executor executor, agrpc::GrpcContext* grpc_context) {
  auto& makers_ = *this;
  makers_.map_order_item_result_to_order_state = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMapOrderItemResultToOrderState(std::move(context), environment);
  };
  makers_.map_to_order_processed = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMapToOrderProcessed(std::move(context), environment);
  };
  makers_.map_to_order_state = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeMapToOrderState(std::move(context), environment);
  };
  makers_.order_processed_endpoint_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::KafkaEndpointConfig& config) {
    return functions::MakeOrderProcessedEndpointSink(std::move(context), environment, config);
  };
  makers_.process_order_item_sink = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::GrpcEndpointConfig& config) {
    return functions::MakeProcessOrderItemSink(std::move(context), environment, config);
  };
  makers_.process_order_items = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeProcessOrderItems(std::move(context), environment);
  };
  makers_.process_order_source = [](servicelib::Context context, servicelib::IServiceEnvironment& environment, const servicelib::config::HttpEndpointConfig& config) {
    return functions::MakeProcessOrderSource(std::move(context), environment, config);
  };
  makers_.soft_deadline = [](servicelib::Context context, servicelib::IServiceEnvironment& environment) {
    return functions::MakeSoftDeadline(std::move(context), environment);
  };
  makers_.http_router = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config)
      -> boost::asio::awaitable<std::shared_ptr<servicelib::http::Router>> {
    (void)context;
    (void)environment;
    (void)config;
    co_return std::make_shared<servicelib::http::Router>();
  };
  makers_.http_server = [executor](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config,
      std::shared_ptr<servicelib::http::Router> router)
      -> boost::asio::awaitable<std::unique_ptr<servicelib::http::Server>> {
    (void)context;
    if (config.httpPort < 0 || config.httpPort > 65535) {
      throw std::invalid_argument("service HTTP port is out of range");
    }
    servicelib::http::Server::Options options;
    options.address = config.httpHost.empty() ? std::string{"0.0.0.0"}
                                               : config.httpHost;
    options.port = static_cast<std::uint16_t>(config.httpPort);
    options.tracingEnabled = environment.getTracing() != nullptr;
    options.shutdownTimeout =
        std::chrono::milliseconds{std::max(config.shutdownTimeout, 0)};
    co_return std::make_unique<servicelib::http::Server>(
        executor, std::move(router), std::move(options));
  };

  makers_.inventory_service_api_client = [grpc_context](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcDataConnectorConfig& config)
      -> boost::asio::awaitable<std::unique_ptr<
          servicelib::grpc_transport::ClientPool<::inventoryserviceapi::InventoryServiceApi::Stub>>> {
    (void)context;
    (void)environment;
    if (config.connectionsCount < 1) {
      throw std::invalid_argument(
          "gRPC connector " + config.name +
          " connectionsCount must be at least 1");
    }
    co_return std::make_unique<
        servicelib::grpc_transport::ClientPool<::inventoryserviceapi::InventoryServiceApi::Stub>>(
        *grpc_context, config.address,
        static_cast<std::size_t>(config.connectionsCount),
        [] (std::shared_ptr<::grpc::Channel> channel) {
          return ::inventoryserviceapi::InventoryServiceApi::NewStub(std::move(channel));
        });
  };
}


}  // namespace example::order_service::app