// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/asio.hpp>
#include <servicelib/runtime/detail/grpc_client.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasink/kafka/librdkafka.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>



namespace example::order_service::app {

class ServiceGenerated;

struct ServiceMakers final {
  std::function<boost::asio::awaitable<std::unique_ptr<functions::MapOrderItemResultToOrderState>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> map_order_item_result_to_order_state;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::MapToOrderProcessed>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> map_to_order_processed;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::MapToOrderState>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> map_to_order_state;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::OrderProcessedEndpointSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_sink;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::ProcessOrderItemSink>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::GrpcEndpointConfig&)> process_order_item_sink;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::ProcessOrderItems>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> process_order_items;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::ProcessOrderSource>>(
      servicelib::Context, servicelib::IServiceEnvironment&, const servicelib::config::HttpEndpointConfig&)> process_order_source;
  std::function<boost::asio::awaitable<std::unique_ptr<functions::SoftDeadline>>(
      servicelib::Context, servicelib::IServiceEnvironment&)> soft_deadline;
    std::function<boost::asio::awaitable<
        std::shared_ptr<servicelib::http::Router>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&)> http_router;
    std::function<boost::asio::awaitable<
        std::unique_ptr<servicelib::http::Server>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&,
        std::shared_ptr<servicelib::http::Router>)> http_server;

    std::function<boost::asio::awaitable<std::unique_ptr<
        servicelib::grpc_transport::ClientPool<::inventoryserviceapi::InventoryServiceApi::Stub>>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::GrpcDataConnectorConfig&)> inventory_service_api_client;

  void initMakers(boost::asio::any_io_executor executor, agrpc::GrpcContext* grpc_context);
};

}  // namespace example::order_service::app