// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include "orderservice/internal/app/makers.generated.hpp"
#include "orderservice/internal/app/functions.generated.hpp"
#include "orderservice/internal/app/streams.generated.hpp"
#include "orderservice/internal/app/bindings.generated.hpp"
#include "orderservice/internal/app/endpoints.generated.hpp"
#include "orderservice/internal/app/connectors.generated.hpp"
#include "orderservice/internal/app/clients.generated.hpp"
#include "orderservice/internal/app/servers.generated.hpp"
#include "orderservice/internal/app/substreams.generated.hpp"

namespace example::order_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  ServiceGenerated(boost::asio::any_io_executor executor,
                   agrpc::GrpcContext& grpc_context,

                   std::shared_ptr<const config::Config> config,
                   servicelib::log::Logger& logger,
                   servicelib::metrics::Metrics& metrics,
                   servicelib::tracing::Tracing* tracing = nullptr);
  ~ServiceGenerated() override;

  boost::asio::awaitable<void> start();
  boost::asio::awaitable<void> stop(servicelib::Context context = {});
  boost::asio::awaitable<void> waitStopped();

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;




  std::shared_ptr<servicelib::datasource::http::IBeastEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;

 protected:
  using ServiceMakers = example::order_service::app::ServiceMakers;
  using ServiceFunctions = example::order_service::app::ServiceFunctions;
  ServiceMakers makers_;
  ServiceFunctions functions_;
  virtual boost::asio::awaitable<void> customMakersInit(servicelib::Context) { co_return; }
  virtual boost::asio::awaitable<void> customFunctionsInit(servicelib::Context) { co_return; }
  virtual boost::asio::awaitable<void> serviceInit() { co_return; }
  virtual boost::asio::awaitable<void> serviceStarted() { co_return; }
  virtual boost::asio::awaitable<void> serviceStopping() { co_return; }

 private:
  friend struct ServiceServers;
  friend struct ServiceEndpoints;
  boost::asio::awaitable<void> initRuntime(servicelib::Context context);
  boost::asio::awaitable<void> stopImpl(servicelib::Context context);
  boost::asio::awaitable<void> stopRuntime(servicelib::Context context = {});
  void releaseRuntime() noexcept;
  ServiceStreams streams_;
  ServiceBindings bindings_;
  ServiceEndpoints endpoints_;
  ServiceConnectors connectors_;
  ServiceClients clients_;
  ServiceServers servers_;
  ServiceSubStreams substreams_;

  boost::asio::any_io_executor executor_;
  agrpc::GrpcContext* grpc_context_;

  std::shared_ptr<const config::Config> config_;
  std::shared_ptr<const servicelib::config::RuntimeConfig> runtime_config_;
  servicelib::log::Logger* logger_;
  servicelib::metrics::Metrics* metrics_;
  servicelib::tracing::Tracing* tracing_;
  bool lifecycle_started_{false};
  std::mutex shutdown_mutex_;
  std::optional<servicelib::detail::ShutdownTask> shutdown_task_;
};


}  // namespace example::order_service::app