// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <servicelib/runtime/detail/initialization.hpp>

namespace example::order_service::app {

boost::asio::awaitable<void> ServiceServers::initInfrastructure(
    ServiceGenerated& service, servicelib::Context context, [[maybe_unused]] const config::Config& cfg,
    const servicelib::config::ServiceConfig& service_config) {
  auto& makers_ = service.makers_;
  auto& servers_ = *this;
  auto executor_ = service.executor_;
  if (!makers_.http_router || !makers_.http_server) {
    throw std::logic_error("HTTP infrastructure makers are not configured");
  }

  servers_.http_router_ = co_await makers_.http_router(context, service, service_config);
  if (!servers_.http_router_) {
    throw std::logic_error("HTTP router maker returned null");
  }
  std::stop_source maker_cancellation;
  std::mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<boost::asio::awaitable<void>> maker_tasks;
  const auto launch = [&](auto task) {
    maker_tasks.push_back(std::move(task));
  };
  launch([](ServiceGenerated* service,
            servicelib::config::ServiceConfig service_config,
            servicelib::Context maker_context,
            std::stop_source* maker_cancellation,
            std::mutex* maker_error_mutex,
            std::exception_ptr* first_maker_error)
             -> boost::asio::awaitable<void> {
    try {
      service->servers_.http_server_ = co_await service->makers_.http_server(
          maker_context, *service, service_config, service->servers_.http_router_);
      if (!service->servers_.http_server_) {
        throw std::logic_error("HTTP server maker returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
  }(&service, service_config, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error));

  if (!makers_.inventory_service_api_client) {
    throw std::logic_error("infrastructure maker inventory_service_api_client is not configured");
  }
  launch([](ServiceGenerated* service,
            servicelib::config::GrpcDataConnectorConfig connector_config,
            servicelib::Context maker_context,
            std::stop_source* maker_cancellation,
            std::mutex* maker_error_mutex,
            std::exception_ptr* first_maker_error)
             -> boost::asio::awaitable<void> {
    try {
      service->clients_.inventory_service_api_client = co_await service->makers_.inventory_service_api_client(
          maker_context, *service, connector_config);
      if (!service->clients_.inventory_service_api_client) {
        throw std::logic_error("infrastructure maker inventory_service_api_client returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
  }(&service, cfg.dataConnectors.inventoryServiceApi, maker_context,
    &maker_cancellation, &maker_error_mutex, &first_maker_error));
  try {
    co_await servicelib::detail::AwaitInitializationGroup(executor_, std::move(maker_tasks), maker_cancellation);
  } catch (...) {
    if (!first_maker_error) first_maker_error = std::current_exception();
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}


}  // namespace example::order_service::app