// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/status/http.hpp>

namespace example::order_service::app {

ServiceGenerated::ServiceGenerated(
    boost::asio::any_io_executor executor,
    agrpc::GrpcContext& grpc_context,

    std::shared_ptr<const config::Config> config,
    servicelib::log::Logger& logger,
    servicelib::metrics::Metrics& metrics,
    servicelib::tracing::Tracing* tracing)
    : executor_(std::move(executor)),
      grpc_context_(&grpc_context),

      config_(std::move(config)),
      logger_(&logger),
      metrics_(&metrics),
      tracing_(tracing) {
  if (!executor_) {
    throw std::invalid_argument("service Asio executor is not initialized");
  }
  if (!config_) {
    throw std::invalid_argument("service config is null");
  }
  runtime_config_ =
      servicelib::config::detail::MakeRuntimeConfigSnapshot(config_);
}

ServiceGenerated::~ServiceGenerated() {
  // Asynchronous shutdown is explicitly awaited by the owning host.
  // Shutdown tasks retain that host until admitted operations are drained.
  releaseRuntime();
}

boost::asio::awaitable<void> ServiceGenerated::start() {
  std::exception_ptr startup_failure;
  try {
    const servicelib::Context context;
    servicelib::config::RuntimeConfigRegistry::Publish(runtime_config_);
    co_await serviceInit();
    makers_.initMakers(executor_, grpc_context_);
    co_await customMakersInit(context);
    co_await initRuntime(context);
    co_await servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    lifecycle_started_ = true;
    servers_.http_server_->Start();
    co_await serviceStarted();
  } catch (...) {
    startup_failure = std::current_exception();
  }
  if (startup_failure) {
    co_await stop();
    std::rethrow_exception(startup_failure);
  }
}

boost::asio::awaitable<void> ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  this->ensureConfiguredPools();
  const auto service_config = getServiceConfigSnapshot();
  if (!service_config) {
    throw std::runtime_error("service config is null");
  }
  co_await servers_.initInfrastructure(*this, context, *config_snapshot, *service_config);
  co_await functions_.initFunctions(context, *config_snapshot, *this, makers_, executor_);
  co_await customFunctionsInit(context);
  streams_.initStreams(*config_snapshot, *this);
  streams_.build(*config_snapshot, *this, functions_, bindings_);
  substreams_.bind(streams_);
  endpoints_.initDataSinks(*this, *config_snapshot);

  endpoints_.initDataSources(*this, *config_snapshot);
  servicelib::http::RegisterStatusRoutes(
      *servers_.http_router_, *this, [this] {
        if (const auto* prometheus =
                dynamic_cast<const servicelib::metrics::PrometheusMetrics*>(
                    metrics_)) {
          return prometheus->Expose();
        }
        return std::string{};
      }, service_config->statusHandler, service_config->metricsHandler,
      service_config->startupHandler, service_config->readinessHandler,
      service_config->livenessHandler);
}

boost::asio::awaitable<void> ServiceGenerated::stop(servicelib::Context context) {
  try {
    auto lifetime = getShutdownLifetime();
    if (!lifetime) {
      // An externally owned service cannot safely outlive its caller.
      co_await stopImpl(context);
      co_return;
    }
    if (const auto config = getServiceConfigSnapshot();
        config && config->shutdownTimeout > 0) {
      context = context.bounded(
          std::chrono::milliseconds{config->shutdownTimeout});
    }
    std::optional<servicelib::detail::ShutdownTask> task;
    {
      std::lock_guard lock(shutdown_mutex_);
      if (!shutdown_task_) {
        shutdown_task_.emplace([this, context, lifetime = std::move(lifetime)]() -> boost::asio::awaitable<void> {
          co_await stopImpl(context);
          co_await waitForShutdown();
        });
      }
      task = shutdown_task_;
    }
    if (co_await task->wait(context)) {
      if (auto error = co_await task->get()) std::rethrow_exception(error);
    }
  } catch (const std::exception& error) {
    try {
      getLogger().error("generated service shutdown failed",
                       {servicelib::log::Field::Err(error.what())});
    } catch (...) {
    }
  } catch (...) {
    try {
      getLogger().error("generated service shutdown failed");
    } catch (...) {
    }
  }
}

boost::asio::awaitable<void> ServiceGenerated::waitStopped() {
  std::optional<servicelib::detail::ShutdownTask> task;
  {
    std::lock_guard lock(shutdown_mutex_);
    task = shutdown_task_;
  }
  if (task) {
    if (auto error = co_await task->get()) std::rethrow_exception(error);
  } else {
    co_await waitForShutdown();
  }
}

boost::asio::awaitable<void> ServiceGenerated::stopImpl(servicelib::Context context) {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (lifecycle_started_) {
      lifecycle_started_ = false;
      co_await serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  co_await stopRuntime(context);
}

boost::asio::awaitable<void> ServiceGenerated::stopRuntime(servicelib::Context context) {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  if (servers_.http_server_) {
    co_await servers_.http_server_->Stop();
    co_await servers_.http_server_->WaitStopped();
  }
  co_await clients_.stop();

  try {
    co_await servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop(context);
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  clients_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
  servers_.http_server_.reset();
  servers_.http_router_.reset();
  servicelib::config::RuntimeConfigRegistry::Publish({});
}

std::shared_ptr<
    servicelib::datasource::http::IBeastEndpoint>
ServiceGenerated::httpDataSourceEndpoint(int endpoint_id) const {
  if (auto endpoint = connectors_.order_service_api_source
          ? connectors_.order_service_api_source->endpoint(endpoint_id) : nullptr) {
    return endpoint;
  }
  throw std::invalid_argument(
      "HTTP datasource endpoint not found: " + std::to_string(endpoint_id));
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return *logger_;
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return *metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return tracing_;
}


}  // namespace example::order_service::app