// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>

#include <functional>
#include <exception>
#include <future>
#include <mutex>
#include <stop_token>
#include <vector>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/asio.hpp>
#include <servicelib/runtime/detail/grpc_client.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasink/kafka/librdkafka.hpp>

#include <example/model/types/order_item.hpp>
#include <example/model/types/order_item_result.hpp>
#include <example/model/types/order_processed.hpp>
#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


#include "orderservice/internal/app/bindings.generated.hpp"

namespace example::order_service::app {

class ServiceGenerated;

  using ProcessOrderInput =
      servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
                              ServiceGenerated>;


struct ServiceFunctions;
struct ServiceStreams final {
  servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>* process_order{};
  servicelib::StreamBase* split_pipeline{nullptr};
  servicelib::StreamBase* process_order_items{nullptr};
  servicelib::SinkEndpointStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, example::order_service::types::OrderState> process_order_item;
  servicelib::StreamBase* map_order_item_result_to_order_state{nullptr};
  servicelib::StreamBase* soft_deadline{nullptr};
  servicelib::StreamBase* map_to_order_state{nullptr};
  servicelib::StreamBase* merge_results{nullptr};
  servicelib::StreamBase* split_order_result{nullptr};
  servicelib::StreamBase* map_to_order_processed{nullptr};
  servicelib::SinkEndpointStreamRef<example::model::types::OrderProcessed, std::monostate, std::exception_ptr> publish_order_processed;

  void initStreams(const config::Config& cfg, ServiceGenerated& service);
  void build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions_, ServiceBindings& bindings_);
};

}  // namespace example::order_service::app