// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::order_service::app {

void ServiceSubStreams::bind(const ServiceStreams& streams) {
  (void)streams;
}

}  // namespace example::order_service::app